/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedOrgsRouteImport } from './routes/_authenticated/orgs'
import { Route as AuthenticatedHiresHireIdRouteImport } from './routes/_authenticated/hires.$hireId'
import { Route as OauthConnectorReturnRouteImport } from './routes/oauth/$connector/return'
import { Route as ApiPublicOnboardingHealthRouteImport } from './routes/api/public/onboarding/health'
import { Route as ApiPublicOnboardingHireUpdateRouteImport } from './routes/api/public/onboarding/hire-update'
import { Route as ApiPublicOnboardingTaskUpdateRouteImport } from './routes/api/public/onboarding/task-update'
import { Route as ApiPublicSlackEventsRouteImport } from './routes/api/public/slack/events'
import { Route as ApiPublicViasocketOrgSlugHireRouteImport } from './routes/api/public/viasocket/$orgSlug/hire'
import { Route as ApiPublicViasocketOrgSlugTaskRouteImport } from './routes/api/public/viasocket/$orgSlug/task'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsRoute = AuthenticatedOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHiresHireIdRoute =
  AuthenticatedHiresHireIdRouteImport.update({
    id: '/hires/$hireId',
    path: '/hires/$hireId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const OauthConnectorReturnRoute = OauthConnectorReturnRouteImport.update({
  id: '/oauth/$connector/return',
  path: '/oauth/$connector/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOnboardingHealthRoute =
  ApiPublicOnboardingHealthRouteImport.update({
    id: '/api/public/onboarding/health',
    path: '/api/public/onboarding/health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOnboardingHireUpdateRoute =
  ApiPublicOnboardingHireUpdateRouteImport.update({
    id: '/api/public/onboarding/hire-update',
    path: '/api/public/onboarding/hire-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOnboardingTaskUpdateRoute =
  ApiPublicOnboardingTaskUpdateRouteImport.update({
    id: '/api/public/onboarding/task-update',
    path: '/api/public/onboarding/task-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSlackEventsRoute = ApiPublicSlackEventsRouteImport.update({
  id: '/api/public/slack/events',
  path: '/api/public/slack/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicViasocketOrgSlugHireRoute =
  ApiPublicViasocketOrgSlugHireRouteImport.update({
    id: '/api/public/viasocket/$orgSlug/hire',
    path: '/api/public/viasocket/$orgSlug/hire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicViasocketOrgSlugTaskRoute =
  ApiPublicViasocketOrgSlugTaskRouteImport.update({
    id: '/api/public/viasocket/$orgSlug/task',
    path: '/api/public/viasocket/$orgSlug/task',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/orgs': typeof AuthenticatedOrgsRoute
  '/hires/$hireId': typeof AuthenticatedHiresHireIdRoute
  '/oauth/$connector/return': typeof OauthConnectorReturnRoute
  '/api/public/onboarding/health': typeof ApiPublicOnboardingHealthRoute
  '/api/public/onboarding/hire-update': typeof ApiPublicOnboardingHireUpdateRoute
  '/api/public/onboarding/task-update': typeof ApiPublicOnboardingTaskUpdateRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/viasocket/$orgSlug/hire': typeof ApiPublicViasocketOrgSlugHireRoute
  '/api/public/viasocket/$orgSlug/task': typeof ApiPublicViasocketOrgSlugTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/orgs': typeof AuthenticatedOrgsRoute
  '/hires/$hireId': typeof AuthenticatedHiresHireIdRoute
  '/oauth/$connector/return': typeof OauthConnectorReturnRoute
  '/api/public/onboarding/health': typeof ApiPublicOnboardingHealthRoute
  '/api/public/onboarding/hire-update': typeof ApiPublicOnboardingHireUpdateRoute
  '/api/public/onboarding/task-update': typeof ApiPublicOnboardingTaskUpdateRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/viasocket/$orgSlug/hire': typeof ApiPublicViasocketOrgSlugHireRoute
  '/api/public/viasocket/$orgSlug/task': typeof ApiPublicViasocketOrgSlugTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/orgs': typeof AuthenticatedOrgsRoute
  '/_authenticated/hires/$hireId': typeof AuthenticatedHiresHireIdRoute
  '/oauth/$connector/return': typeof OauthConnectorReturnRoute
  '/api/public/onboarding/health': typeof ApiPublicOnboardingHealthRoute
  '/api/public/onboarding/hire-update': typeof ApiPublicOnboardingHireUpdateRoute
  '/api/public/onboarding/task-update': typeof ApiPublicOnboardingTaskUpdateRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/viasocket/$orgSlug/hire': typeof ApiPublicViasocketOrgSlugHireRoute
  '/api/public/viasocket/$orgSlug/task': typeof ApiPublicViasocketOrgSlugTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/dashboard'
    | '/integrations'
    | '/orgs'
    | '/hires/$hireId'
    | '/oauth/$connector/return'
    | '/api/public/onboarding/health'
    | '/api/public/onboarding/hire-update'
    | '/api/public/onboarding/task-update'
    | '/api/public/slack/events'
    | '/api/public/viasocket/$orgSlug/hire'
    | '/api/public/viasocket/$orgSlug/task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approvals'
    | '/dashboard'
    | '/integrations'
    | '/orgs'
    | '/hires/$hireId'
    | '/oauth/$connector/return'
    | '/api/public/onboarding/health'
    | '/api/public/onboarding/hire-update'
    | '/api/public/onboarding/task-update'
    | '/api/public/slack/events'
    | '/api/public/viasocket/$orgSlug/hire'
    | '/api/public/viasocket/$orgSlug/task'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/orgs'
    | '/_authenticated/hires/$hireId'
    | '/oauth/$connector/return'
    | '/api/public/onboarding/health'
    | '/api/public/onboarding/hire-update'
    | '/api/public/onboarding/task-update'
    | '/api/public/slack/events'
    | '/api/public/viasocket/$orgSlug/hire'
    | '/api/public/viasocket/$orgSlug/task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OauthConnectorReturnRoute: typeof OauthConnectorReturnRoute
  ApiPublicOnboardingHealthRoute: typeof ApiPublicOnboardingHealthRoute
  ApiPublicOnboardingHireUpdateRoute: typeof ApiPublicOnboardingHireUpdateRoute
  ApiPublicOnboardingTaskUpdateRoute: typeof ApiPublicOnboardingTaskUpdateRoute
  ApiPublicSlackEventsRoute: typeof ApiPublicSlackEventsRoute
  ApiPublicViasocketOrgSlugHireRoute: typeof ApiPublicViasocketOrgSlugHireRoute
  ApiPublicViasocketOrgSlugTaskRoute: typeof ApiPublicViasocketOrgSlugTaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs': {
      id: '/_authenticated/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthenticatedOrgsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hires/$hireId': {
      id: '/_authenticated/hires/$hireId'
      path: '/hires/$hireId'
      fullPath: '/hires/$hireId'
      preLoaderRoute: typeof AuthenticatedHiresHireIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/$connector/return': {
      id: '/oauth/$connector/return'
      path: '/oauth/$connector/return'
      fullPath: '/oauth/$connector/return'
      preLoaderRoute: typeof OauthConnectorReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onboarding/health': {
      id: '/api/public/onboarding/health'
      path: '/api/public/onboarding/health'
      fullPath: '/api/public/onboarding/health'
      preLoaderRoute: typeof ApiPublicOnboardingHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onboarding/hire-update': {
      id: '/api/public/onboarding/hire-update'
      path: '/api/public/onboarding/hire-update'
      fullPath: '/api/public/onboarding/hire-update'
      preLoaderRoute: typeof ApiPublicOnboardingHireUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onboarding/task-update': {
      id: '/api/public/onboarding/task-update'
      path: '/api/public/onboarding/task-update'
      fullPath: '/api/public/onboarding/task-update'
      preLoaderRoute: typeof ApiPublicOnboardingTaskUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/events': {
      id: '/api/public/slack/events'
      path: '/api/public/slack/events'
      fullPath: '/api/public/slack/events'
      preLoaderRoute: typeof ApiPublicSlackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/viasocket/$orgSlug/hire': {
      id: '/api/public/viasocket/$orgSlug/hire'
      path: '/api/public/viasocket/$orgSlug/hire'
      fullPath: '/api/public/viasocket/$orgSlug/hire'
      preLoaderRoute: typeof ApiPublicViasocketOrgSlugHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/viasocket/$orgSlug/task': {
      id: '/api/public/viasocket/$orgSlug/task'
      path: '/api/public/viasocket/$orgSlug/task'
      fullPath: '/api/public/viasocket/$orgSlug/task'
      preLoaderRoute: typeof ApiPublicViasocketOrgSlugTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedOrgsRoute: typeof AuthenticatedOrgsRoute
  AuthenticatedHiresHireIdRoute: typeof AuthenticatedHiresHireIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedOrgsRoute: AuthenticatedOrgsRoute,
  AuthenticatedHiresHireIdRoute: AuthenticatedHiresHireIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OauthConnectorReturnRoute: OauthConnectorReturnRoute,
  ApiPublicOnboardingHealthRoute: ApiPublicOnboardingHealthRoute,
  ApiPublicOnboardingHireUpdateRoute: ApiPublicOnboardingHireUpdateRoute,
  ApiPublicOnboardingTaskUpdateRoute: ApiPublicOnboardingTaskUpdateRoute,
  ApiPublicSlackEventsRoute: ApiPublicSlackEventsRoute,
  ApiPublicViasocketOrgSlugHireRoute: ApiPublicViasocketOrgSlugHireRoute,
  ApiPublicViasocketOrgSlugTaskRoute: ApiPublicViasocketOrgSlugTaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
